---
stages:
  - build-docs
  - publish-docs

build-docs-html:
  stage: build-docs
  image: python:3.8
  script:
    - apt update && apt install python3-enchant -y
    - pip install -U pip setuptools wheel nox
    - nox -e docs
    - mv docs/_build/html html
  artifacts:
    paths:
      - html
    expire_in: 30 days

pages:
  stage: publish-docs
  image: debian:bullseye-slim
  script:
    - mv html public
    - 'echo "Gitlab Pages available at: ${CI_PAGES_URL}"'
  artifacts:
    paths:
      - public
    expire_in: 30 days

upload-tags:
  stage: upload
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_TAG != null && $CI_PROJECT_PATH == $CICD_UPSTREAM_PATH'
  variables:
    ARTIFACT_PIPELINE_ID: $CI_PIPELINE_ID
    GITLAB_PROJECT_PATH: "saltstack%2Fopen%2Fsalt-ext%2Fsalt-ext-modules-vmware"
    DOCS_PATH: "docs.saltproject.io/salt/extensions/salt-ext-modules-vmware/en/latest"
    RCLONE_OPTIONS: "sync -c -v"
  trigger:
    project: saltstack/open/docs/docs-upload
    strategy: depend
