# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
import saltext.vmware.modules.esxi as esxi
import pytest


def test_esxi_get_lun_ids_should_return_lun_NAA_ids(service_instance, integration_test_config):
    expected_lun_ids = integration_test_config["esxi_datastore_disk_names"]
    actual_ids = esxi.get_lun_ids(service_instance=service_instance)
    assert actual_ids == expected_lun_ids


@pytest.mark.parametrize(
    'arg_name', [
        "vmotionSupported",
        "standbySupported",
        "ipmiSupported",
        "maxSupportedVMs",
        "recursiveResourcePoolsSupported",
        "cpuMemoryResourceConfigurationSupported",
        "rebootSupported",
        "shutdownSupported",
        "maxRunningVMs",
        "maxSupportedVcpus",
        "maxRegisteredVMs",
        "datastorePrincipalSupported",
        "sanSupported",
        "nfsSupported",
        "iscsiSupported",
        "vlanTaggingSupported",
        "nicTeamingSupported",
        "highGuestMemSupported",
        "maintenanceModeSupported",
        "suspendedRelocateSupported",
        "restrictedSnapshotRelocateSupported",
        "perVmSwapFiles",
        "localSwapDatastoreSupported",
        "unsharedSwapVMotionSupported",
        "backgroundSnapshotsSupported",
        "preAssignedPCIUnitNumbersSupported",
        "screenshotSupported",
        "scaledScreenshotSupported",
        "storageVMotionSupported",
        "vmotionWithStorageVMotionSupported",
        "vmotionAcrossNetworkSupported",
        "maxNumDisksSVMotion",
        "hbrNicSelectionSupported",
        "vrNfcNicSelectionSupported",
        "recordReplaySupported",
        "ftSupported",
        "replayUnsupportedReason",
        "smpFtSupported",
        "maxVcpusPerFtVm",
        "loginBySSLThumbprintSupported",
        "cloneFromSnapshotSupported",
        "deltaDiskBackingsSupported",
        "perVMNetworkTrafficShapingSupported",
        "tpmSupported",
        "virtualExecUsageSupported",
        "storageIORMSupported",
        "vmDirectPathGen2Supported",
        "vmDirectPathGen2UnsupportedReasonExtended",
        "vStorageCapable",
        "snapshotRelayoutSupported",
        "firewallIpRulesSupported",
        "servicePackageInfoSupported",
        "maxHostRunningVms",
        "maxHostSupportedVcpus",
        "vmfsDatastoreMountCapable",
        "eightPlusHostVmfsSharedAccessSupported",
        "nestedHVSupported",
        "vPMCSupported",
        "interVMCommunicationThroughVMCISupported",
        "scheduledHardwareUpgradeSupported",
        "featureCapabilitiesSupported",
        "latencySensitivitySupported",
        "storagePolicySupported",
        "accel3dSupported",
        "reliableMemoryAware",
        "multipleNetworkStackInstanceSupported",
        "messageBusProxySupported",
        "vsanSupported",
        "vFlashSupported",
        "hostAccessManagerSupported",
        "provisioningNicSelectionSupported",
        "nfs41Supported",
        "nfs41Krb5iSupported",
        "turnDiskLocatorLedSupported",
        "virtualVolumeDatastoreSupported",
        "markAsSsdSupported",
        "markAsLocalSupported",
        "smartCardAuthenticationSupported",
        "cryptoSupported",
        "oneKVolumeAPIsSupported",
        "gatewayOnNicSupported",
        "upitSupported",
        "cpuHwMmuSupported",
        "encryptedVMotionSupported",
        "encryptionChangeOnAddRemoveSupported",
        "encryptionHotOperationSupported",
        "encryptionWithSnapshotsSupported",
        "encryptionFaultToleranceSupported",
        "encryptionMemorySaveSupported",
        "encryptionRDMSupported",
        "encryptionVFlashSupported",
        "encryptionCBRCSupported",
        "encryptionHBRSupported",
        "supportedVmfsMajorVersion",
        "vmDirectPathGen2UnsupportedReason",
        "ftCompatibilityIssues",
        "smpFtCompatibilityIssues",
        "replayCompatibilityIssues"
    ]
)
def test_esxi_host_capability_params(service_instance, integration_test_config, arg_name):
    capabilities = esxi.get_capabilities(service_instance=service_instance)
    for host_id in capabilities:
        expected_value = integration_test_config['esxi_capabilities'][host_id][arg_name]
        assert capabilities[host_id][arg_name] == expected_value